### ISSUE TITLE
Installation issues: yajl

### ISSUE THREAD

**Issue by h2rashee** [AMDmi3/jsonslicer#47]
It seems to be having an issue finding `yajl`.
```
(env) $ pip install jsonslicer
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting jsonslicer
  Using cached jsonslicer-0.1.6.tar.gz (24 kB)
    ERROR: Command errored out with exit status 1:
     command: /users/h2rashee/code/env/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t8DUc_/jsonslicer/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t8DUc_/jsonslicer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vepEnL
         cwd: /tmp/pip-install-t8DUc_/jsonslicer/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-t8DUc_/jsonslicer/setup.py", line 31
        print('MISSING DEPENDENCY: yajl library not found, please install it to continue', file=sys.stderr)
                                                                                               ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

but I have it locally. Run immediately after
```
(env) $ pip freeze
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
pkg-resources==0.0.0
yajl==0.3.5
```

I've tried re-installing and wiping out my environment but this seems to be very reproducible for me.

**Comment by AMDmi3** [comment]
Python 2 is not supported.

**Comment by mspanish** [comment]
I get the same error using Python 3.7, with yajl installed - maybe I need 0.3.5?

**Comment by AMDmi3** [comment]
> I get the same error using Python 3.7, with yajl 0.3.5 installed

You need yajl native library, not python module.

**Comment by hw-monkey** [comment]
I used Visual Studio to install yajl. Message indicates success:
```
  [0/1] Install the project...
  -- Install configuration: "Debug"
  -- Up-to-date: D:/Price_Transparency_Insurance/yajl-master/out/install/x64-Debug/lib/yajl.lib
  -- Up-to-date: D:/Price_Transparency_Insurance/yajl-master/out/install/x64-Debug/lib/yajl.dll
  -- Up-to-date: D:/Price_Transparency_Insurance/yajl-master/out/install/x64-Debug/lib/yajl_s.lib
  -- Up-to-date: D:/Price_Transparency_Insurance/yajl-master/out/install/x64-Debug/include/yajl/yajl_parse.h
  -- Up-to-date: D:/Price_Transparency_Insurance/yajl-master/out/install/x64-Debug/include/yajl/yajl_gen.h
  -- Up-to-date: D:/Price_Transparency_Insurance/yajl-master/out/install/x64-Debug/include/yajl/yajl_common.h
  -- Up-to-date: D:/Price_Transparency_Insurance/yajl-master/out/install/x64-Debug/include/yajl/yajl_tree.h
  -- Up-to-date: D:/Price_Transparency_Insurance/yajl-master/out/install/x64-Debug/include/yajl/yajl_version.h
  -- Up-to-date: D:/Price_Transparency_Insurance/yajl-master/out/install/x64-Debug/share/pkgconfig/yajl.pc
  -- Up-to-date: D:/Price_Transparency_Insurance/yajl-master/out/install/x64-Debug/bin/json_reformat.exe
  -- Up-to-date: D:/Price_Transparency_Insurance/yajl-master/out/install/x64-Debug/bin/json_verify.exe
Install succeeded.
```
Next, receive message about yajl not installed
```
C:\Python\Python310-64>python -m pip install jsonslicer
Collecting jsonslicer
  Using cached jsonslicer-0.1.7.tar.gz (22 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      MISSING DEPENDENCY: yajl library not found, please install it to continue

      See http://lloyd.github.io/yajl/ for installation instructions, or install
      it from your package manager
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
When more explicitly called, I receive same result:
`.\python.exe -m pip install --global-option=build_ext --global-option='-LD:/Price_Transparency_Insurance/yajl-master/out/install/x64-Debug/lib' --global-option='-ID:/Price_Transparency_Insurance/yajl-master/out/install/x64-Debug/include/yajl' --global-option='-lyajl' jsonslicer`

**Comment by AMDmi3** [comment]
> MISSING DEPENDENCY: yajl library not found, please install it to continue

The error suggests that `pkg-config` cannot find installed yajl, e.h. `pkg-config --libs --cflags yajl` fails. You may need to add `D:/Price_Transparency_Insurance/yajl-master/out/install/x64-Debug/share/pkgconfig` to `PKG_CONFIG_PATH` or something like that.

> When more explicitly called, I receive same result:

I do not get where this line comes from. The arguments look right though, were they manually provided?

**Comment by hw-monkey** [comment]
> to `PKG_CONFIG_PATH` or something like that.

Added `export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:D:/Price_Transparency_Insurance/yajl-master/out/install/x64-Debug/share/pkgconfig` with no success.
> The arguments look right though, were they manually provided?

I attempted to manually force the installation libdir and includedir. I used the details the autogenerated D:\Price_Transparency_Insurance\yajl-master\out\install\x64-Debug\share\pkgconfig\yajl.pc file which indicates the following:
```
prefix=D:/Price_Transparency_Insurance/yajl-master/out/install/x64-Debug
libdir=${prefix}/lib
includedir=${prefix}/include/yajl

Name: Yet Another JSON Library
Description: A Portable JSON parsing and serialization library in ANSI C
Version: 2.1.1
Cflags: -I${includedir}
Libs: -L${libdir} -lyajl
```
I also tried `python -m pip install --no-clean jsonslicer` to preserve the temp files. When doing this, I see that the `dependency_links.txt` is empty.

**Comment by hw-monkey** [comment]
I recompiled yajl at a more global level on the machine. I also have focused on my syntax. Now, it seems the error is jsonslicer compiling specific.

```
Microsoft Windows [Version 10.0.19044.1766]
(c) Microsoft Corporation. All rights reserved.


C:\Python\Python310-64>set PKG_CONFIG_PATH=C:/Program Files (x86)/YetAnotherJSONParser/share/pkgconfig;%PKG_CONFIG_PATH%

C:\Python\Python310-64>.\python.exe -m pip install --global-option="build_ext" --global-option="-Lc:/pkgs/yajl/lib/" --global-option="-Ic:/pkgs/yajl/include/" jsonslicer
WARNING: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
Collecting jsonslicer
  Using cached jsonslicer-0.1.7.tar.gz (22 kB)
  Preparing metadata (setup.py) ... done
Skipping wheel build for jsonslicer, due to binaries being disabled for it.
Installing collected packages: jsonslicer
  Running setup.py install for jsonslicer ... error
  error: subprocess-exited-with-error

  × Running setup.py install for jsonslicer did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      running build_ext
      building 'jsonslicer' extension
      creating build
      creating build\temp.win-amd64-3.10
      creating build\temp.win-amd64-3.10\Release
      creating build\temp.win-amd64-3.10\Release\src
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/Program -Ic:/pkgs/yajl/include/ -IC:\Python\Python310-64\include -IC:\Python\Python310-64\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /EHsc /Tpsrc/construct_handlers.cc /Fobuild\temp.win-amd64-3.10\Release\src/construct_handlers.obj -std=c++11 -DJSONSLICER_VERSION="0.1.7" -DUSE_BYTES_INTERNALLY -fno-exceptions -fno-rtti
      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      cl : Command line warning D9002 : ignoring unknown option '-fno-exceptions'
      cl : Command line warning D9002 : ignoring unknown option '-fno-rtti'
      construct_handlers.cc
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/Program -Ic:/pkgs/yajl/include/ -IC:\Python\Python310-64\include -IC:\Python\Python310-64\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /EHsc /Tpsrc/encoding.cc /Fobuild\temp.win-amd64-3.10\Release\src/encoding.obj -std=c++11 -DJSONSLICER_VERSION="0.1.7" -DUSE_BYTES_INTERNALLY -fno-exceptions -fno-rtti
      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      cl : Command line warning D9002 : ignoring unknown option '-fno-exceptions'
      cl : Command line warning D9002 : ignoring unknown option '-fno-rtti'
      encoding.cc
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/Program -Ic:/pkgs/yajl/include/ -IC:\Python\Python310-64\include -IC:\Python\Python310-64\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /EHsc /Tpsrc/handlers.cc /Fobuild\temp.win-amd64-3.10\Release\src/handlers.obj -std=c++11 -DJSONSLICER_VERSION="0.1.7" -DUSE_BYTES_INTERNALLY -fno-exceptions -fno-rtti
      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      cl : Command line warning D9002 : ignoring unknown option '-fno-exceptions'
      cl : Command line warning D9002 : ignoring unknown option '-fno-rtti'
      handlers.cc
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/Program -Ic:/pkgs/yajl/include/ -IC:\Python\Python310-64\include -IC:\Python\Python310-64\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /EHsc /Tpsrc/jsonslicer_construction.cc /Fobuild\temp.win-amd64-3.10\Release\src/jsonslicer_construction.obj -std=c++11 -DJSONSLICER_VERSION="0.1.7" -DUSE_BYTES_INTERNALLY -fno-exceptions -fno-rtti
      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      cl : Command line warning D9002 : ignoring unknown option '-fno-exceptions'
      cl : Command line warning D9002 : ignoring unknown option '-fno-rtti'
      jsonslicer_construction.cc
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/Program -Ic:/pkgs/yajl/include/ -IC:\Python\Python310-64\include -IC:\Python\Python310-64\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /EHsc /Tpsrc/jsonslicer_iteration.cc /Fobuild\temp.win-amd64-3.10\Release\src/jsonslicer_iteration.obj -std=c++11 -DJSONSLICER_VERSION="0.1.7" -DUSE_BYTES_INTERNALLY -fno-exceptions -fno-rtti
      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      cl : Command line warning D9002 : ignoring unknown option '-fno-exceptions'
      cl : Command line warning D9002 : ignoring unknown option '-fno-rtti'
      jsonslicer_iteration.cc
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/Program -Ic:/pkgs/yajl/include/ -IC:\Python\Python310-64\include -IC:\Python\Python310-64\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /EHsc /Tpsrc/jsonslicer_type.cc /Fobuild\temp.win-amd64-3.10\Release\src/jsonslicer_type.obj -std=c++11 -DJSONSLICER_VERSION="0.1.7" -DUSE_BYTES_INTERNALLY -fno-exceptions -fno-rtti
      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      cl : Command line warning D9002 : ignoring unknown option '-fno-exceptions'
      cl : Command line warning D9002 : ignoring unknown option '-fno-rtti'
      jsonslicer_type.cc
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/Program -Ic:/pkgs/yajl/include/ -IC:\Python\Python310-64\include -IC:\Python\Python310-64\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /EHsc /Tpsrc/output_formatting.cc /Fobuild\temp.win-amd64-3.10\Release\src/output_formatting.obj -std=c++11 -DJSONSLICER_VERSION="0.1.7" -DUSE_BYTES_INTERNALLY -fno-exceptions -fno-rtti
      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      cl : Command line warning D9002 : ignoring unknown option '-fno-exceptions'
      cl : Command line warning D9002 : ignoring unknown option '-fno-rtti'
      output_formatting.cc
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/Program -Ic:/pkgs/yajl/include/ -IC:\Python\Python310-64\include -IC:\Python\Python310-64\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /EHsc /Tpsrc/py_module.cc /Fobuild\temp.win-amd64-3.10\Release\src/py_module.obj -std=c++11 -DJSONSLICER_VERSION="0.1.7" -DUSE_BYTES_INTERNALLY -fno-exceptions -fno-rtti
      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      cl : Command line warning D9002 : ignoring unknown option '-fno-exceptions'
      cl : Command line warning D9002 : ignoring unknown option '-fno-rtti'
      py_module.cc
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/Program -Ic:/pkgs/yajl/include/ -IC:\Python\Python310-64\include -IC:\Python\Python310-64\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /EHsc /Tpsrc/pymutindex.cc /Fobuild\temp.win-amd64-3.10\Release\src/pymutindex.obj -std=c++11 -DJSONSLICER_VERSION="0.1.7" -DUSE_BYTES_INTERNALLY -fno-exceptions -fno-rtti
      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      cl : Command line warning D9002 : ignoring unknown option '-fno-exceptions'
      cl : Command line warning D9002 : ignoring unknown option '-fno-rtti'
      pymutindex.cc
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/Program -Ic:/pkgs/yajl/include/ -IC:\Python\Python310-64\include -IC:\Python\Python310-64\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /EHsc /Tpsrc/pyobjlist.cc /Fobuild\temp.win-amd64-3.10\Release\src/pyobjlist.obj -std=c++11 -DJSONSLICER_VERSION="0.1.7" -DUSE_BYTES_INTERNALLY -fno-exceptions -fno-rtti
      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      cl : Command line warning D9002 : ignoring unknown option '-fno-exceptions'
      cl : Command line warning D9002 : ignoring unknown option '-fno-rtti'
      pyobjlist.cc
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/Program -Ic:/pkgs/yajl/include/ -IC:\Python\Python310-64\include -IC:\Python\Python310-64\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /EHsc /Tpsrc/seek_handlers.cc /Fobuild\temp.win-amd64-3.10\Release\src/seek_handlers.obj -std=c++11 -DJSONSLICER_VERSION="0.1.7" -DUSE_BYTES_INTERNALLY -fno-exceptions -fno-rtti
      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      cl : Command line warning D9002 : ignoring unknown option '-fno-exceptions'
      cl : Command line warning D9002 : ignoring unknown option '-fno-rtti'
      seek_handlers.cc
      creating C:\Users\ea0032\AppData\Local\Temp\pip-install-6vxw5a6o\jsonslicer_8e02e974a3534c2db17c6cb5ba1b00f2\build\lib.win-amd64-3.10
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:/Program /LIBPATH:c:/pkgs/yajl/lib/ /LIBPATH:C:\Python\Python310-64\libs /LIBPATH:C:\Python\Python310-64\PCbuild\amd64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\lib\x64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.19041.0\\um\x64 yajl.lib /EXPORT:PyInit_jsonslicer build\temp.win-amd64-3.10\Release\src/construct_handlers.obj build\temp.win-amd64-3.10\Release\src/encoding.obj build\temp.win-amd64-3.10\Release\src/handlers.obj build\temp.win-amd64-3.10\Release\src/jsonslicer_construction.obj build\temp.win-amd64-3.10\Release\src/jsonslicer_iteration.obj build\temp.win-amd64-3.10\Release\src/jsonslicer_type.obj build\temp.win-amd64-3.10\Release\src/output_formatting.obj build\temp.win-amd64-3.10\Release\src/py_module.obj build\temp.win-amd64-3.10\Release\src/pymutindex.obj build\temp.win-amd64-3.10\Release\src/pyobjlist.obj build\temp.win-amd64-3.10\Release\src/seek_handlers.obj /OUT:build\lib.win-amd64-3.10\jsonslicer.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.10\Release\src\jsonslicer.cp310-win_amd64.lib
         Creating library build\temp.win-amd64-3.10\Release\src\jsonslicer.cp310-win_amd64.lib and object build\temp.win-amd64-3.10\Release\src\jsonslicer.cp310-win_amd64.exp
      jsonslicer_construction.obj : error LNK2001: unresolved external symbol yajl_free
      jsonslicer_construction.obj : error LNK2001: unresolved external symbol yajl_alloc
      jsonslicer_construction.obj : error LNK2001: unresolved external symbol yajl_config
      jsonslicer_iteration.obj : error LNK2001: unresolved external symbol yajl_free_error
      jsonslicer_iteration.obj : error LNK2001: unresolved external symbol yajl_parse
      jsonslicer_iteration.obj : error LNK2001: unresolved external symbol yajl_complete_parse
      jsonslicer_iteration.obj : error LNK2001: unresolved external symbol yajl_get_error
      build\lib.win-amd64-3.10\jsonslicer.cp310-win_amd64.pyd : fatal error LNK1120: 7 unresolved externals
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> jsonslicer

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.


```

**Comment by AMDmi3** [comment]
Microsoft compiler is not supported.
